server:
    port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/marcosnasp/spring-config-baeldung-tutorial.git
          timeout: 10
          clone-on-start: true
  security:
    user:
      name: root
      password: s3cr3t